variables:
  sql_file_name:
    description: SQL file to use for the run
    default: metadata_d_group_facets_vhp_insert_script.sql

  sql_subfolder:
    description: SQL subfolder
    default: metadata

resources:
  jobs:
    setup_data_platform_db:
      name: setup_data_platform_db
      description: |
        This job sets up all tables by executing the sql script passed to the job.      
      tags:
        - data_platform
        - setup
        - configuration

      timeout_seconds: 3600
      max_concurrent_runs: 1

      tasks:
        - task_key: setup_tables
          description: "Execute SQL script to create and populate DLT metadata tables"
          sql_task:
            file:            
              path: ${var.resource_path}/sql/${var.sql_subfolder}/${var.sql_file_name}
            warehouse_id: ${var.warehouse_id}
          timeout_seconds: 1800
          retry_on_timeout: false
          # max_retries: 1
          # min_retry_interval_millis: 10000
    
        # email_notifications:
        #   on_start: []
        #   on_success: []
        #   on_failure: []

        # # Optional: Schedule to run daily at 2 AM (commented out by default)
        # # schedule:
        # #   quartz_cron_expression: "0 0 2 * * ?"
        # #   timezone_id: "America/Chicago"
        # #   pause_status: "UNPAUSED"

      # # Parameters that can be overridden when running the job
      parameters:
        - name: catalog
          default: "${var.catalog}" 
        - name: schema
          default: "${var.bronze_schema}" 